add_lunch_combo axxion_d2lte-userdebug
add_lunch_combo axxion_gee-userdebug
add_lunch_combo axxion_i9300-userdebug
add_lunch_combo axxion_i9500-userdebug
add_lunch_combo axxion_jflte-userdebug
add_lunch_combo axxion_m8-userdebug
add_lunch_combo axxion_maguro-userdebug
add_lunch_combo axxion_mako-userdebug
add_lunch_combo axxion_spyder-userdebug
add_lunch_combo axxion_umts_spyder-userdebug
add_lunch_combo axxion_p760-userdebug
add_lunch_combo axxion_p765-userdebug
add_lunch_combo axxion_p768-userdebug

