add_lunch_combo axxion_d2lte-userdebug
add_lunch_combo axxion_gee-userdebug
add_lunch_combo axxion_jflte-userdebug
add_lunch_combo axxion_maguro-userdebug
add_lunch_combo axxion_mako-userdebug
add_lunch_combo axxion_spyder-userdebug
add_lunch_combo axxion_umts_spyder-userdebug
